config/routes.rb
# routes
Rails.application.routes.draw do
  devise_for :users
  get 'static_pages/hello'

  resources :users, only: [:show, :index]
 
  root 'phrases#index'
  post '/phrases' => 'phrases#create'
  get '/phrases/new' => 'phrases#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  WillPaginate.per_page = 10
end

app/models/phrase.rb
class Phrase < ApplicationRecord
  CATEGORIES = {
    'Actions' => 0,
    'Time' => 1,
    'Productivity' => 2,
    'Apologies' => 3,
    'Common' => 4
  }.freeze

  validates :phrase, :translation, presence: true
  validates :phrase, uniqueness: true
  validates :category,
            inclusion: {
              in: CATEGORIES,
              message: '%<value> is not a valid categoty'
            }

  enum category: CATEGORIES
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attr_writer :login
  validate :validate_username

  validates :username, presence: true

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase}]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

end

app/controllers/phrases_controller.rb
# phrases controller
class PhrasesController < ApplicationController
  def index
    @phrases = Phrase.paginate(page: params[:page], per_page: 10)
  end

  def new
    @phrase = Phrase.new
  end

  def create
    @phrase = Phrase.new(phrase_params)
    if @phrase.save
      flash[:notice] = 'Phrase has been created!'
      # redirect_to phrases_path
      redirect_to root_path
    else
      flash[:danger] = @phrase.errors.full_messages.to_sentence
      render :new
    end
  end

  private

  def phrase_params
    values = params.require(:phrase).permit(:phrase, :translation, :category)
    values[:category] = values[:category].to_i
    values
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def hello
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find_by(id: params[:id])
    end
    
      def index
        @users = User.paginate(:page => params[:page], per_page: 10)
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phrases_helper.rb
module PhrasesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.slim
.navbar-fixed-bottom.row-fluid.text-center
  .navbar-inner
    .container
      footer.footer
        .small#footerRight
          | Copyright © 2020 Leviossa Company

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Phrases</a>
  
 <div class="navbar-nav"><%= link_to 'New Phrase', phrases_new_path, class: 'nav-link'%></div>
 <div class="navbar-nav"><%= link_to 'Users', users_path, class: 'nav-link'%></div>

 <div class="navbar-nav"><%= link_to 'Current User', user_path(current_user), class: 'nav-link'%></div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
      <li class="nav-item">
       <%= link_to 'Edit profile', edit_user_registration_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
       <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
      </li>
      <% else %>
      <li class="nav-item">
       <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
       <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.slim
doctype html
html
  head
    title RailsTutorial
    meta name="viewport" content="width=device-width, initial-scale=1.0"
     = stylesheet_link_tag    "application", media: 'all', 'data-turbolinks-track' => true
     = javascript_pack_tag "application", 'data-turbolinks-track' => true
     = csrf_meta_tags


  body
    .row
      = render 'layouts/navbar'
      .col-md-6.col-md-offset-3
        - flash.each do |key, value|
          div class="alert alert-#{key}"
            = value

        = yield

        = render 'layouts/footer'

app/views/phrases/_phrase.slim
tr
  td = phrase.id
  td = phrase.phrase
  td = phrase.translation
  td = phrase.category

app/views/phrases/index.slim
h1 Listing phrases

table.table
  tr
    th Id
    th Phrase
    th Translation
    th Category

  - @phrases.each do |phrase|
    = render phrase


.text-center
  = will_paginate @phrases, renderer: BootstrapPagination::Rails

app/views/phrases/new.slim
= form_for(@phrase) do |f|
    h1 Create Phrase
    .form-group
        = f.label :phrase
        br
        = f.text_field :phrase, :class => 'form-control'

    .form-group
        = f.label :translation
        br
        = f.text_field :translation, :class => 'form-control'

    .form-group
        = f.label :category
        br
        = f.select :category, Phrase::CATEGORIES, {}, { :class => 'form-control' }

    = f.submit 'Submit', :class => 'btn btn-primary'

app/views/static_pages/hello.slim
.text-center
  h1 ЗДАРОВА БРАТИШКА
  p КАК У ТЕБЯ ДЕЛИШКИ?

app/views/users/_user.slim
tr
  td = user.id
  td = user.username
  td = user.email
  td = user.created_at
  td = user.updated_at

app/views/users/index.slim
h1 Listing users

table.table
  tr
    th Id
    th Username
    th Email
    th Created At
    th Updated At

  - @users.each do |user|
    = render user


.text-center
  = will_paginate @users, renderer: BootstrapPagination::Rails

app/views/users/show.slim
.container-fluid
  .row
    .col-md-12
      h1 Username: #{@user.username}